
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.GeneralMenu__InitializeVirtual__Patch.Postfix(GeneralMenu)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Supprimer le paramètre inutilisé", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.LoadingCustomMusic__OnEventCustomMusicScanComplete__Patch.Postfix(LoadingCustomMusic,Events.Audio.CustomMusicScanComplete.Data)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.LoadingCustomMusic__OnEventLoadingCustomMusic__Patch.Postfix(LoadingCustomMusic,Events.Audio.CustomMusicScanningFolder.Data)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.LoadingCustomMusic__OnEventCustomMusicScanComplete__Patch.Postfix(LoadingCustomMusic,Events.Audio.CustomMusicScanComplete.Data)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.LoadingCustomMusic__OnEventCustomMusicScanStarted__Patch.Postfix(LoadingCustomMusic,Events.Audio.CustomMusicScanStarted.Data)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Supprimer le paramètre inutilisé", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.LoadingCustomMusic__OnEventCustomMusicScanStarted__Patch.Postfix(LoadingCustomMusic,Events.Audio.CustomMusicScanStarted.Data)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Supprimer le paramètre inutilisé", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.LoadingCustomMusic__OnEventLoadingCustomMusic__Patch.Postfix(LoadingCustomMusic,Events.Audio.CustomMusicScanningFolder.Data)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.MenuDescriptionLabel__SetText__Patch.Transpiler(System.Collections.Generic.IEnumerable{Harmony.CodeInstruction})~System.Collections.Generic.IEnumerable{Harmony.CodeInstruction}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.ProfilesMenuProfileButton__SetName__Patch.Postfix(ProfilesMenuProfileButton)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.SubtitleLogic__OnSubtitleEvent__Patch.Prefix(SubtitleLogic,Events.Audio.SubtitleEvent.Data)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.SubtitleLogic__Start__Patch.Postfix(SubtitleLogic)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.SubtitleLogic__Update__Patch.Postfix(SubtitleLogic)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:La valeur attribuée au symbole n'est jamais utilisée", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.SubtitleLogic__Update__Patch.Postfix(SubtitleLogic)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.UILabel__OnStart__Patch.Postfix(UILabel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.VRManager__OnStart__Patch.Postfix(VRManager,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Supprimer le paramètre inutilisé", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.VRManager__OnStart__Patch.Postfix(VRManager,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:La valeur attribuée au symbole n'est jamais utilisée", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Harmony.VRManager__OnStart__Patch.Postfix(VRManager,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.LanguageMenu.LanguageMenuController.Start")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.LanguageMenu.LanguageMenuController.Update")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.LanguageMenu.Update")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:La valeur attribuée au symbole n'est jamais utilisée", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Modules.PauseMenuModule.LevelInfo~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:La valeur attribuée au symbole n'est jamais utilisée", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.Modules.PauseMenuModule.LevelName~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.UnityScripts.UILabelTranslate.LateUpdate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Distance.Translator.UnityScripts.UILabelTranslate.Start")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Qualité du code", "IDE0051:Supprimer les membres privés non utilisés", Justification = "<En attente>", Scope = "member", Target = "~M:Menu.CreateMenu``1(Spectrum.API.Interfaces.Systems.IManager,System.String,System.String,System.String)")]